name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual triggering for debugging

# Cancel in-progress runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint, Type Check, Test & Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true # Stop on first failure

    steps:
      # Stage 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better analysis

      # Stage 2: Setup Environment
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      # Stage 3: Install Dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Stage 4: Format Check (Mandatory - Failure is build failure)
      - name: Check code formatting
        run: pnpm run format:check

      # Stage 5: Lint (Mandatory - Failure is build failure)
      - name: Run ESLint
        run: pnpm run lint

      # Stage 6: Type Check (Mandatory - Failure is build failure)
      - name: Run TypeScript type checking
        run: pnpm run typecheck

      # Stage 7: Test with Coverage (Mandatory - Failure is build failure)
      - name: Run tests with coverage
        run: pnpm run test:coverage

      # Upload coverage reports as artifacts
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

      # Stage 8: Build (Mandatory - Failure is build failure)
      - name: Build TypeScript
        run: pnpm run build

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/
          retention-days: 7

      # Stage 9: Performance Benchmarks (Mandatory - Failure is build failure)
      - name: Run CLI performance benchmarks
        run: pnpm run benchmark:cli:ci

      # Stage 10: Security Vulnerability Scan (Mandatory)
      - name: Run security audit
        run: pnpm audit --audit-level=high
        continue-on-error: false # Fail on high/critical vulnerabilities

  # Summary job to ensure all checks passed
  ci-success:
    name: CI Success
    needs: [ci]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: CI Pipeline Success
        run: echo "✅ All CI checks passed successfully!"
